services:
  auth-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: auth-service
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - mysql
    env_file:
      - .env
    networks:
      - app_genesis_network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=auth_password
    command: ["redis-server", "--requirepass", "auth_password"]
    networks:
      - app_genesis_network

  mysql:
    image: mysql:5.7
    container_name: auth_mysql
    volumes:
      - auth_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - "3306:3306"
    entrypoint: |
      bash -c "
      mkdir -p /var/run/mysqld && \
      chown mysql:mysql /var/run/mysqld && \
      chmod 750 /var/run/mysqld && \
      exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=ON --secure-file-priv=/var/lib/mysql-files --tls-version=TLSv1.2 --pid-file=/var/run/mysqld/mysqld.pid
      "
    networks:
      - app_genesis_network

networks:
  app_genesis_network:
    external: true

volumes:
  auth_mysql_data:
  redis-data:
