services:
  nginx_production:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: nginx_production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./http.d:/etc/nginx/http.d
      - ./conf:/etc/nginx/conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - app_genesis_network

networks:
  app_genesis_network:
    external: true
